# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cb173b3f342146b7b80aa2134b0d9ddeffd93ee0addb67b19094fd039ffc876cf84b3a6b0874bcc2903f179454d137f2ffc1c847601576b8494ff3c39a5ad9d

test:
  secret_key_base: f5d287ce4aa88377ea271b8b99fae084f3af9b46740be70144a2b9d39c0ebfd81bbe25ac005260c841bf3937bb94b8d59f15dc3802c8b055d4fb0cd9c8cdcd59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
